Initial commit of the slapd-config role
stuvusIT/slapd-config pull request #1
Opened 2017-03-16 18:13 UTC by dasJ

2017-03-18 10:10 UTC, Scriptkiddi reviewed
da ich keine ahnung von slapd hab brauch ich hier für den review mal

2017-03-31 14:03 UTC, Mr-Pi requested changes
Warum nutzt du hier soviel `builtin`?

2017-03-31 14:03 UTC, Mr-Pi commented on README.md
> +Check out the `slapd-base` for this purpose.
Nutze doch nen Link zur role.

2017-03-31 14:03 UTC, Mr-Pi commented on README.md
> +A dpkg- or pacman-based Linux distribution.
Wollen wir Arch supporten?

2017-03-31 14:03 UTC, Mr-Pi commented on README.md
> +**All variables must be quoted when they contain spaces!**"
Was genau ist damit gemein?

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-attribute-upsert
> +search="$(builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "${dn}" -s base "${attribute}" | grep "^${attribute}:")"
Hey geil die option habe ich ewig gesucht und jetzt hier gefunden ;)

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-attribute-upsert
> +
Bitte auf valide Argumente prüfen, von mir aus reicht sowas:
`[ $# -ne 4 -a $# -ne 3 ] && echo "USAGE $0 <socket(without leading ldapi://)> <binddn> <dn> <attribute(optional)>`

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-attribute-upsert
> +shift 4
Wenn du das oben prüfst kann as shift hier weg.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-attribute-upsert
> +set +e
Warum deaktivierst du die sensitive shell hier wieder?

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-attribute-upsert
> +search="$(builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "${dn}" -s base "${attribute}" | grep "^${attribute}:")"
Kannst du statt /dev/stdin nicht '-' nutzen, wäre schöner(würde div. bash Richtlinien entsprechen).

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-attribute-upsert
> +			if [[ ! "${searchline}" =~ ^"${attribute}":\ (\{[[:digit:]]*\})?"${param}"$ ]]; then
warum `[[`?

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-create-mdb
> +
Wie oben bitte auf valide Argumente prüfen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-create-monitor
> +
Argumente prüfen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-attribute-upsert
> +search="$(builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "${dn}" -s base "${attribute}" | grep "^${attribute}:")"
Die Zeile vielleicht besser auf mehre strecken, entweder nach den pipes umbrechen oder `\` nutzen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-create-mdb
> +builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "olcDatabase={2}mdb,cn=config" -s base "dn"
Die Zeile vielleicht besser auf mehre strecken, entweder nach den pipes umbrechen oder `\` nutzen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-create-monitor
> +builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "olcDatabase={1}monitor,cn=config" -s base "dn"
Die Zeile vielleicht besser auf mehre strecken, entweder nach den pipes umbrechen oder `\` nutzen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-create-overlay
> +search="$(builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "${database}" -s sub "dn")"
Die Zeile vielleicht besser auf mehre strecken, entweder nach den pipes umbrechen oder `\` nutzen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-create-overlay
> +
Bitte die Argumente prüfen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-global-modules
> +set -o nounset
Bitte die Argument prüfen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-global-modules
> +alreadyThere="$(builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b 'cn=modules{0},cn=config' -s base olcModuleLoad)"
Die Zeile vielleicht besser auf mehre strecken, entweder nach den pipes umbrechen oder `\` nutzen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-olc-attribute-clean
> +search="$(builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "${dn}" -s base | grep "^olc")"
Die Zeile vielleicht besser auf mehre strecken, entweder nach den pipes umbrechen oder `\` nutzen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-olc-attribute-clean
> +EOF
Ne leerzeile wäre schön ;)

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-overlay-attribute-upsert
> +search="$(builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "${dn}" -s base "${attribute}" | grep "^${attribute}:")"
Die Zeile vielleicht besser auf mehre strecken, entweder nach den pipes umbrechen oder `\` nutzen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-overlay-dn
> +search="$(builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "${db}" -s sub dn)"
Die Zeile vielleicht besser auf mehre strecken, entweder nach den pipes umbrechen oder `\` nutzen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-overlay-attribute-upsert
> +
Bitte Argumente prüfen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-olc-attribute-clean
> +
Bitte Argumente Prüfen.

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-global-schema
> +
Bitte Argumente prüfen

2017-03-31 14:03 UTC, Mr-Pi commented on files/slapd-overlay-attribute-upsert
> +builtin echo -n "${bindpw}" | ldapmodify -H "${socket}" -D "${binddn}" -y /dev/stdin -f /dev/shm/modattrs.ldif
Was soll das builtin hier?

2017-03-31 14:09 UTC, Mr-Pi requested changes
Bitte auch noch immer in den scripten die Argumente checken.

2017-03-31 14:09 UTC, Mr-Pi commented on meta/main.yml
> +  - name: Debian
Debian versionen (jessie)

2017-03-31 14:09 UTC, Mr-Pi commented on meta/main.yml
> +dependencies: []
slapd-base adden?

2017-03-31 14:09 UTC, Mr-Pi commented on tasks/frontend-config.yml
> +  command: /usr/local/bin/slapd-attribute-upsert "{{ ldapi_socket | urlencode() | regex_replace('/', '%2F') }}" "{{ olc_rootdn }}" "olcDatabase={-1}frontend,cn=config" {{ item.key }} {% if item.value
in mehre Zeilen bringen, zur besseren Lesbarkeit?

2017-03-31 14:09 UTC, Mr-Pi commented on tasks/frontend-config.yml
> +  command: /usr/local/bin/slapd-olc-attribute-clean "{{ ldapi_socket | urlencode() | regex_replace('/', '%2F') }}" "{{ olc_rootdn }}" "olcDatabase={-1}frontend,cn=config" {{ frontend_config | join('
hier auch

2017-03-31 14:09 UTC, Mr-Pi commented on tasks/global-config.yml
> +  command: /usr/local/bin/slapd-attribute-upsert "{{ ldapi_socket | urlencode() | regex_replace('/', '%2F') }}" "{{ olc_rootdn }}" "cn=config" {{ item.key }} {% if item.value is iterable and item.val
In mehrere Zeilen bringen zur besseren Lesbarkeit.

2017-03-31 14:09 UTC, Mr-Pi commented on tasks/global-config.yml
> +  command: /usr/local/bin/slapd-olc-attribute-clean "{{ ldapi_socket | urlencode() | regex_replace('/', '%2F') }}" "{{ olc_rootdn }}" "cn=config" {{ default_global_config | combine(global_config) | j
In mehrere Zeilen bringen zur besseren Lesbarkeit

2017-03-31 14:09 UTC, Mr-Pi commented on tasks/global-modules.yml
> +  command: /usr/local/bin/slapd-global-modules "{{ ldapi_socket | urlencode() | regex_replace('/', '%2F') }}" "{{ olc_rootdn }}" "{{ modules_path }}" "{{ enable_monitor }}" {% if additional_modules i
In mehrere Zeilen bringen zur besseren Lesbarkeit

2017-03-31 14:09 UTC, Mr-Pi commented on tasks/global-schemas.yml
> +  command: /usr/local/bin/slapd-global-schema "{{ ldapi_socket | urlencode() | regex_replace('/', '%2F') }}" "{{ olc_rootdn }}" "{{ item }}" "{{ olc_dir }}"
In mehrere Zeilen bringen zur besseren Lesbarkeit

2017-03-31 14:09 UTC, Mr-Pi commented on tasks/mdb-config.yml
> +  command: /usr/local/bin/slapd-attribute-upsert "{{ ldapi_socket | urlencode() | regex_replace('/', '%2F') }}" "{{ olc_rootdn }}" "olcDatabase={2}mdb,cn=config" {{ item.key }} {% if item.value is it
In mehrere Zeilen bringen zur besseren Lesbarkeit

2017-03-31 14:09 UTC, Mr-Pi commented on tasks/monitor-config.yml
> +  command: /usr/local/bin/slapd-attribute-upsert "{{ ldapi_socket | urlencode() | regex_replace('/', '%2F') }}" "{{ olc_rootdn }}" "olcDatabase={1}monitor,cn=config" {{ item.key }} {% if item.value i
In mehrere Zeilen bringen zur besseren Lesbarkeit

2017-03-31 14:09 UTC, Mr-Pi commented on tasks/olc-config.yml
> +  command: /usr/local/bin/slapd-attribute-upsert "{{ ldapi_socket | urlencode() | regex_replace('/', '%2F') }}" "{{ olc_rootdn }}" "olcDatabase={0}config,cn=config" {{ item.key }} {% if item.value is
In mehrere Zeilen bringen zur besseren Lesbarkeit

2017-04-01 15:48 UTC, dasJ commented on README.md
> +A dpkg- or pacman-based Linux distribution.
Ja

2017-04-01 15:48 UTC, dasJ commented on files/slapd-attribute-upsert
> +
Wieso? Wird doch eh nur von Ansible aufgerufen

2017-04-01 15:49 UTC, dasJ commented on files/slapd-attribute-upsert
> +set +e
Weil die Suche != 0 zurückgeben kann

2017-04-01 15:49 UTC, dasJ commented on files/slapd-attribute-upsert
> +search="$(builtin echo -n "${bindpw}" | ldapsearch -o ldif-wrap=no -H "${socket}" -D "${binddn}" -y /dev/stdin -b "${dn}" -s base "${attribute}" | grep "^${attribute}:")"
Das ist doch ein Feature vom ausführenden Programm, nicht von der bash

2017-04-01 15:49 UTC, dasJ commented on files/slapd-attribute-upsert
> +			if [[ ! "${searchline}" =~ ^"${attribute}":\ (\{[[:digit:]]*\})?"${param}"$ ]]; then
Regular expressions

2017-04-01 15:50 UTC, dasJ commented on meta/main.yml
> +dependencies: []
Davon häng ich ja eigentlich nicht direkt ab, siehe readme

2017-04-01 15:55 UTC, dasJ commented on files/slapd-attribute-upsert
> +shift 4
Kann es nicht, wil ich später über `$@` iteriere

2017-04-01 16:13 UTC, dasJ commented
builtin ist um zu erzwingen, dass die bash keinen `echo` Prozess spawnt. Dann würde das Passwort in der Command Line von echo stehen

2017-04-10 13:17 UTC, Mr-Pi approved these changes

2017-04-10 13:17 UTC, merged