Various little fixes
stuvusIT/slapd-config pull request #9
Opened 2017-06-04 23:27 UTC by dasJ

- Namespace variables
- Copy helper scripts we need
- Fix names of helper scripts
- Use default('') to prevent NullPointerExceptions

2017-06-05 12:55 UTC, SlothOfAnarchy requested changes

2017-06-05 12:55 UTC, SlothOfAnarchy commented on defaults/main.yml
> +  dummy: value
are these dummy entries really needed? Can't you create an empty dict?

2017-06-05 12:55 UTC, SlothOfAnarchy commented on vars/main.yml
> +  olcDbDirectory: "{{ slapd_mdb_dir | mandatory }}"
please mention and describe mandatory vars by name in readme. Also you forgot to replace usages of `db_dir` in readme.

2017-06-05 14:00 UTC, dasJ commented on defaults/main.yml
> +  dummy: value
I cannot

2017-06-05 14:58 UTC, dasJ commented
@SlothOfAnarchy Rebased onto master and fixed the README

2017-06-05 16:19 UTC, SlothOfAnarchy requested changes

2017-06-05 16:19 UTC, SlothOfAnarchy commented on tasks/frontend-config.yml
> +    {{ default_frontend_config | combine(slapd_frontend_config) | join(' ') }} olcAttributeOptions olcConcurrency olcTLSCRLCheck olcTLSVerifyClient olcTLSProtocolMin
there is another use of `frontent_config` in this file that you didn't refactor.

2017-06-05 16:19 UTC, SlothOfAnarchy commented on defaults/main.yml
> +  dummy: value
Can't you check if it is defined when using it? Or try `{}`, this works for me in another role.

2017-06-11 19:12 UTC, dasJ commented
@SlothOfAnarchy Pls rereview

2017-06-11 19:35 UTC, SlothOfAnarchy approved these changes

2017-06-11 19:36 UTC, merged